acumalaka

In [ ]:
print ("Hai ganteng ror")

Hai ganteng ror


In [ ]:
import time
print(time.ctime())

Thu Feb  6 04:41:48 2025


In [ ]:
z = "Hello"
y = 20
c = 30.9
f = ['apple', 'berry']

z,y,c,f
print(z,y,c,f)

('noice', 69, 4.2, ['halo', 'manies'])

In [ ]:
o = int(1)
y = int(2.8)
z = int ("3")
j = str(20)

print (o,y,z,j)

1 2 3 20


In [ ]:
a  = "Hello"
b = " world"
c = a+b
print(c)

Hello world


In [ ]:
a = "Hello World"
print(a[1])

print(len(a))

e
11


In [ ]:
b = "BINUS Univ"
print(b[2:5])

c = "BINUS Univ"
print(c[:5])

d = "BINUS Univ"
print(d[2:])

NUS
BINUS
NUS Univ


In [ ]:
a = "Hello"
print(a.upper())

b = "Hello"
print(b.lower())

c = "Hello"
print(c.replace("H", "J"))


HELLO
hello
Jello


In [ ]:
nama = "sam"
x= 19
string = "nama saya {} umur {}"

print(string.format(nama,x))

nama saya sam umur 19


In [ ]:
nama ="Grace"
for i in enumerate(nama):
  print(i)




(0, 'G')
(1, 'r')
(2, 'a')
(3, 'c')
(4, 'e')


In [ ]:
def perbandingan (a,b):
  if a>b:
    print("a lebih dari b")
  elif a<b:
    print("a kurang dari b")
  else:
    print("a = b")

In [ ]:
perbandingan(4,8)

a kurang dari b


In [ ]:
i = 1
while i<6:
  print(i)
  i += 1

1
2
3
4
5


In [ ]:
i = 3
for i in range(0,6):
  print(i)


0
1
2
3
4
5


In [ ]:
for i in range(2,41):
  if i % 2==0:
    print(i,"Genap\n")
  else:
    print(i,"Ganjil\n")


2 Genap

3 Ganjil

4 Genap

5 Ganjil

6 Genap

7 Ganjil

8 Genap

9 Ganjil

10 Genap

11 Ganjil

12 Genap

13 Ganjil

14 Genap

15 Ganjil

16 Genap

17 Ganjil

18 Genap

19 Ganjil

20 Genap

21 Ganjil

22 Genap

23 Ganjil

24 Genap

25 Ganjil

26 Genap

27 Ganjil

28 Genap

29 Ganjil

30 Genap

31 Ganjil

32 Genap

33 Ganjil

34 Genap

35 Ganjil

36 Genap

37 Ganjil

38 Genap

39 Ganjil

40 Genap



In [ ]:
import numpy as np

In [ ]:
x = np.array([[1,2,3], [3,6,7]])
x

array([[1, 2, 3],
       [3, 6, 7]])

In [ ]:
y = np.array([[8,2,9], [3,5,7]])
y

array([[8, 2, 9],
       [3, 5, 7]])

In [ ]:
print(x+y)

[[ 9  4 12]
 [ 6 11 14]]


In [ ]:
data = np.array ([10,9,8,7,6,5])

print("Rata-rata:",np.mean(data))
print("Maksimum:",np.max(data))
print("Minimum:",np.min(data))
print("Standar Devisiasi:", np.std(data))

Rata-rata: 7.5
Maksimum: 10
Minimum: 5
standar Devisiasi: 1.707825127659933
